name: Mocha test

on: 
 push:
  branches:
   - main
 
jobs:
  build:
 
    runs-on: ubuntu-latest
 
    strategy:
      matrix:
        node-version: [16.x]
 
 
    steps:
    - uses: actions/checkout@v3
    
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: npm install, build, and test
      run: |
        npm install -g mocha
        npm install 
        

      env:
        CI: true

      
      
    - name: testing bot
            
      env:
       CI: true
       TOKEN_BOT: ${{ secrets.ASK_BOT }}
      run: |
        mocha hello.spec.js
     
       
        
 
