name: Mocha test

on: 
 push:
  branches:
   - main
 
jobs:
  build:
 
    runs-on: ubuntu-latest
 
    strategy:
      matrix:
        node-version: [16.x]
 
 
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: npm install, build, and test
      run: |
        npm install -g mocha
        npm install 
        

      env:
        CI: true
    - name: Decrypt secret
      run: ./decrypt_secret.sh
      env: 
       TOKEN_BOT: ${{ secrets.ASK_BOT }}
      
    - name: testing bot
            
      env:
       CI: true
       
      run: |
        mocha hello.spec.js
        mocha indexold.js "TOKEN_BOT"
        cat $HOME/secrets/my_secret.json
       
        
 
