name: Mocha test

on: 
 push:
  branches:
   - main
 
jobs:
  build:
 
    runs-on: ubuntu-latest
 
    strategy:
      matrix:
        node-version: [16.x]
 
 
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: npm install, build, and test
      run: |
        npm install -g mocha
        npm install 
        

      env:
        CI: true
        
    - name: testing bot
      run: |
        mocha hello.spec.js
        mocha indexold.js ${{ secrets.ASK_BOT}}
        
      env:
       CI: true
        
 
